// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';

var Curry            = require("bs-platform/lib/js/curry.js");
var Js_primitive     = require("bs-platform/lib/js/js_primitive.js");
var Board$ReasonLife = require("./Board.bs.js");

function map(f, param) {
  if (param) {
    return /* Some */[Curry._1(f, param[0])];
  } else {
    return /* None */0;
  }
}

function createTable(param) {
  var columns = param[1];
  var table = document.createElement("table");
  table.className = "board";
  for(var r = 0 ,r_finish = param[0] - 1 | 0; r <= r_finish; ++r){
    var tr = document.createElement("tr");
    for(var c = 0 ,c_finish = columns - 1 | 0; c <= c_finish; ++c){
      var td = document.createElement("td");
      td.id = "" + (String(r) + ("-" + (String(c) + "")));
      tr.appendChild(td);
    }
    table.appendChild(tr);
  }
  return table;
}

var size = /* tuple */[
  40,
  60
];

var board = Board$ReasonLife.make(size);

var table = createTable(size);

var root = map((function (param) {
        param.appendChild(table);
        return /* () */0;
      }), Js_primitive.null_to_opt(document.getElementById("root")));

exports.map         = map;
exports.createTable = createTable;
exports.size        = size;
exports.board       = board;
exports.table       = table;
exports.root        = root;
/* board Not a pure module */
